article:
  type: tech # tech/story
  auto_excerpt: 50
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
  share: [wechat, weibo, email, link]

logo:
  subtitle: '欢迎来到浅海深井博客！ | 🤔也许我该会点更多的，这样这里就不会看着这么空旷了'

inject:
  head:
    - <link rel="stylesheet" href="/css/custom-fonts.css">
  script:

api: https://site-info.kyangconn.cn?url=${href}

style:
  font-family: 
    body: '"HarmonyOS Sans SC", sans-serif'

menubar:
  columns: 4
  items:
    # 博客主页
    - id: home
      theme: '#1BCDFC'
      icon: solar:home-2-bold-duotone
      title: 博客
      url: /
    
    # 关于页面
    - id: about
      theme: '#3DC550'
      icon: solar:user-circle-bold-duotone
      title: 关于
      url: /about/
    
    # 友情链接
    - id: friends
      theme: '#E91E63'
      icon: solar:chat-square-like-bold-duotone
      title: 友链
      url: /friends/
    
    # 更多 - 可以是链接集合页或其他
    - id: more
      theme: '#FA6400'
      icon: solar:link-circle-bold-duotone
      title: 更多
      url: /more/

comments:
  service: giscus
  lazyload: true
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    src: https://giscus.app/client.js
    data-repo: kyangconn/kyangconn.github.io
    data-repo-id: R_kgDOOBswVQ
    data-category: Announcements
    data-category-id: DIC_kwDOOBswVc4C5i0W
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous
